### PR TITLE
Bhm v05 1

### PR DESCRIPTION
**Pull request by tdwelly**
This branch add the full set of BHM cartons for v0.5.
Some fine details to be refined (e.g. photometry transforms), but all major components now in place.

### CODE REVIEW

**Comment by tdwelly** [comment]
Hi José
It appears that a single flake8 error has scuppered this merge - but I've no idea of the correct process to fix it within the pull request. So the red cross remains for now.
Cheers
Tom

**Comment by tdwelly** [comment]
ok - minor edit committed to pacify flake8. Should now me good to go!

**Comment by albireox** [comment]
Hi @tdwelly. This all looks good to me. I've merged the optical magnitude PR. That should not affect your code (I think!) but you'll need to merge from main before your merge the PR.

**Review by albireox — APPROVED** [review]

**Comment by tdwelly** [comment]
The merge request required some editing of python/target_selection/config/target_selection.yml

**Pull request merged**
