### PR TITLE
Add MWM Dust Dist program.

### PR DESCRIPTION
**Pull request by schlafly**
This adds the MWM Dust dist program.  Thisi s the same as the normal MWM dust program, changing only names and the dependence on mwm_galactic_core to mwm_galactic_core_dist.

### CODE REVIEW

**Comment by schlafly** [comment]
@jcbird , any interest in reviewing this to make sure I didn't mess up badly?  Here's the relevant diff:
```
$ diff python/target_selection/cartons/mwm_dust_dist.py python/target_selection/cartons/mwm_dust.py
6c6
< # @Filename: mwm_dust_dist.py
---
> # @Filename: mwm_dust.py
112,116c112,113
< class MWM_Dust_Dist_Carton(BaseCarton):
<     """MWM Dust Dist Carton.
<
<     This is identical to the MWM_Dust_Carton, but depending on the
<     mwm_galactic_core_dist rather than mwm_galactic_core carton.
---
> class MWM_Dust_Carton(BaseCarton):
>     """MWM Dust Carton.
149c146
<     name = 'mwm_dust_core_dist'
---
>     name = 'mwm_dust_core'
152c149
<     program = 'mwm_dust_dist'
---
>     program = 'mwm_dust'
162c159
<                      .where(targetdb.Carton.carton == 'mwm_galactic_core_dist',
---
>                      .where(targetdb.Carton.carton == 'mwm_galactic_core',


```

**Comment by jcbird** [comment]
This looks good to me. It is ultimately up to @albireox  and @astronomygupta if they are using the derived class name as a unique ID.

**Comment by albireox** [comment]
This looks initially fine to me. Has the `mwm_galactic_core_dist` already been implemented and run? We should probably wait until that's done and we can test the `_dist` code before merging.

The `mwm_dust_core` carton uses DR3 and removes the TIC, but this one keeps it. Is that something we should change?

**Comment by jcbird** [comment]
I'll let @schlafly confirm, but we should absolutely get rid of TIC and replace with Gaia DR3. Thanks.

**Comment by schlafly** [comment]
Thanks for paying attention.  I did not intend to make any changes wrt TIC.  Honestly, I don't know what TIC is and I would definitely choose Gaia DR3.  Thank you!

**Comment by schlafly** [comment]
> This looks initially fine to me. Has the mwm_galactic_core_dist already been implemented and run? We should probably wait until that's done and we can test the _dist code before merging.

Sorry, I don't know the status here.  The goal on my end is to make sure that the dust carton and GG carton are kept in sync; dust_core_dist with galactic_core_dist, dust_core with galactic_core.  Thanks!

**Comment by albireox** [comment]
Sounds good, I think with your changes we can take care of updating the other bits to using Gaia DR3 the same way we've been doing everywhere else. I'll get to this next week.

**Comment by albireox** [comment]
It took a while but I implemented both `mwm_dust_core` and `mwm_dust_core_dist`. I'm going to close this PR but you can check the updated code in #277. I'll send an email with the location of the test files.

**Pull request closed without merging**
