### PR TITLE
Xmatch psql

### PR DESCRIPTION
**Pull request by johndonor3**
According to Felipe, the changes he made to target_selection/xmatch.py should be kept, and the documentation he added should be kept. It looks like those are the only changes on this branch? So I think it safe to merge, and it is worth merging.

### CODE REVIEW

**Comment by fsantanar** [comment]
Hi Jon and everyone,
thanks for doing this, and sorry for the linting errors, they were hidden within the errors E501 for lines with length between 79 and 99, but I got to see them when ignoring that error. I change the codes catalog_to_catalog.py and xmatch.py to fix that but now the review is failing in isort with codes catalog_to_catalog.py and v1_duplicates_table_creation.py, and I am not sure why. I am using isort 5.2.0 on all 3 codes but for some reason it works for xmatch.py but not for the other 2. Any ideas on why this might be happening?
Cheers and thanks

**Review by fsantanar — COMMENTED** [review]
All is left in my opinion is to fix the isort errors

**Comment by johndonor3** [comment]
I don't think we should spend too much time worrying about isort linting errors.

**Comment by albireox** [comment]
Let me know if you think this is ready to merge, and I'll bypass the failed tests. We should then tag and make sure the tag for v1 in the database matches this.

Then I think we may want to revert some of the changes to `xmatch.py`; I don't want the PSQL to be needed long-term, but maybe that's something to worry about for v2.

**Comment by johndonor3** [comment]
From a not-super-thorough review yesterday, the changes I saw are what Felipe said we should merge. So I think it's ready?

If we're going to tag "V1" I think the PSQL should be included. And as you can we can worry about fixing it for V2. Maybe. Eventually.

**Comment by albireox** [comment]
Yes, v1 should be tagged with the code that was used to generate, PSQL included. I'll merge.

**Pull request merged**
