### PR TITLE
Skies v05

### PR DESCRIPTION
**Pull request by fsantanar**
Slightly updated skies.py script to the version used to create the new entries in catalogdb

### CODE REVIEW

**Review by albireox — CHANGES_REQUESTED** [review]
The changes looks good to me. It seems you'll need to merge from main to solve the conflicts with `ops_skies` and also make sure the tests pass. After that feel free to merge.

**Comment by fsantanar** [comment]
Ok thanks @albireox for the advice. Should I edit skies.py on main and then use the option  "Create a new branch for this commit and start a pull request"? Should I do something to cancel the current pull request?

**Comment by albireox** [comment]
No, just merge main into skies_v05 and fix any conflicts if they exist (there probably are since GH is not letting you merge). The commit the merge with the conflict changes and it should let you merge the PR.

**Comment by fsantanar** [comment]
Ok I merged main into skies_v05 locally and resolved the conflict with ops_skies.py using the version in main so I think skies_v05 then got the new version for ops_skies.py and skies.py, I then committed and pushed. I believe that just now Pramod was able to merge back skies_v05 into main. I am not sure but I think that skies.py produced an error in flake8 at line 290 (?) but I don't see that error running flake8 locally on my laptop in the same script. Thanks a lot José and Pramod

**Pull request merged**
