### PR TITLE
Yanny scraper

### PR DESCRIPTION
**Pull request by tdwelly**
Adding in yanny_scraper code, as discussed.
This is a stand-alone script, but requires adding new dependency on pydl in order to interpret yanny files.

### CODE REVIEW

**Review by albireox — APPROVED** [review]
I made some changes to make sure the linting and building tests pass but I haven't changed anything in the code itself. For future PRs, can you make sure the tests pass?

Feel free to merge when you're ready.

**Comment by tdwelly** [comment]
Hi José, Thanks, yes that required a surprisingly large number of changes! Surprising because 'it just worked' within my fairly stripped down python environment.

Anyway, for future. I'm not familiar with the standard testing process for the sdss packages, is this something built into the cookie cutter template? Can one access it from setup.py? Or do these tests require initiating a pull request via github?

As is probably the case, you will have written a nice readme somewhere that answers all of those stupid questions. If so, I'd be happy with a one URL answer.

**Comment by albireox** [comment]
Most of the commits I made were actually to make target_selection pip installable again. There's something weird with pydl that will fail installing depending on what packages you have already installed in your environment. I ended up upgrading the dependency to 1.0.0rc1 and that seems to work fine.

As for the testing, every time you commit a change or open a PR, GitHub runs some tests (you can see the result in the summary of the PR or going to Actions). Right now it basically just tests linting and import sorting. Just an attempt at making sure the code doesn't diverge too much from the coding standards.

You can see the workflow in this file https://github.com/sdss/target_selection/blob/main/.github/workflows/pythonapp.yml but apart from installing the package, it boils down to running these two command and making sure they don't fail

```
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
isort -c python/
```

You can install flake8 and isort locally and run the commands. They will tell you what went wrong. Or you can open the PR and look at the results of the checks. For now I added an exclude for the BHM carton files. Also, don't spend too much time on that, the purpose of this is to standardise the code a bit, not just follow PEP98 for the sake of it. I can easily fix small problems with linting.

**Comment by tdwelly** [comment]
Thanks for the tips. I'll add those flake8,isort checks into my usual (informal) workflow.

**Pull request merged**
